### ISSUE TITLE
Libraries in lib/ are not included in build process

### ISSUE THREAD

**Issue by maxgerhardt** [nigelb/platform-apollo3blue#41]
See project: https://community.platformio.org/t/dependency-hell-help/30587/4?u=maxgerhardt

For `framework = ambiqsdk-sfe` projects, the libraries in the `lib/` folder of the project are ignored, the LDF fails to find them although every file is at the correct place.

When removing the overwrite (?) of the PIO internal `__PIO_LIB_BUILDERS` variable, the library appears again in the build process / `.vscode/c_cpp_properties.json`.

https://github.com/nigelb/platform-apollo3blue/blob/31e5d7d9db0b42c00739d8b5bf195aff8248a2ac/builder/frameworks/ambiqsuitesdk-sfe.py#L330

It should be investigated what's going on there, and possibly rewrite the build logic to use regular `env.BuildLibrary()` calls with source filters, like I do e.g.  [here](https://github.com/CommunityGD32Cores/platform-gd32/blob/main/builder/frameworks/wifi-sdk.py#L254-L271).

**Comment by nigelb** [comment]
Hi @maxgerhardt,

Thanks for tracking down this issue. 

It isn't that `env['__PIO_LIB_BUILDERS']` is overwritten, it is Prepended after all, but because `env['__PIO_LIB_BUILDERS']` is not None the GetLibBuilder function does not search for any more libraries:
https://github.com/platformio/platformio-core/blob/5ec5660fa65c766b9278f447c785117ff59d7c79/platformio/builder/tools/piolib.py#L1063-L1070

Any advice on how to use `env.BuildLibrary() ` to replicate this kind of library deceleration:
https://github.com/nigelb/platform-apollo3blue/blob/31e5d7d9db0b42c00739d8b5bf195aff8248a2ac/extra/ambiqsdk-sfe/libraries/third_party/FreeRTOS/library.json#L1-L29

or:
https://github.com/nigelb/platform-apollo3blue/blob/31e5d7d9db0b42c00739d8b5bf195aff8248a2ac/extra/ambiqsdk-sfe/libraries/ambiq_ble/profiles/volecommon/library.json#L1-L33

In the mean time I have made this change which seems to do the trick:

```diff
@@ -326,6 +326,5 @@ def configure_upload_address(env, board):
    env.Replace(UPLOAD_ADDRESS=upload_address)

configure_upload_address(env, board)
- env.Prepend(LIBS=libs)
- env.Prepend(LIBS=libs, __PIO_LIB_BUILDERS=lib_builders)
- 
+ env.Prepend(LIBS=libs, __PIO_LIB_BUILDERS=env.GetLibBuilders())
+ env.Append(__PIO_LIB_BUILDERS=lib_builders)
````

**Comment by maxgerhardt** [comment]
>Any advice on how to use env.BuildLibrary() to replicate this kind of library deceleration:

You wouldn't be able to duplicate it exactly with the meta-information and the libraries appearing in the LDF tree, but if they're always needed anyways, that shouldn't matter, they'll be internally built correctly. 

You can basically transofrm the build.flags into CPPDEFINES for `-D` macros and CPPPATH for `-I` flags, and CCFLAGS for any other options. The include directory also as CPPPATH. The source filter can be used exactly the same way too as an optional parameter to `env.BuildLibraries` .

But, if you've already done all this work to write these manifests, and now the `__PIO_LIB_BUILDERS` fix works and has both the SDK-internal and regular libraries in it, I guess such a rewrite is not needed anymore.
